### ISSUE TITLE
add the instance for HasDefaultSqlDataType PgDataTypeSyntax UTCTime

### ISSUE THREAD

**Issue by adetokunbo** [haskell-beam/beam#282]
This looks like an omission, since the corresponding HasSqlValueSyntax instance is provided

```haskell
instance HasSqlValueSyntax PgValueSyntax UTCTime where
  sqlValueSyntax  = defaultPgValueSynatx
```
(using CPP in [Database/Beam/Postgres/Syntax.hs](https://github.com/tathougies/beam/blob/b88ef2ed69815c8440bfdf80afd539055e92e219/beam-postgres/Database/Beam/Postgres/Syntax.hs#L1112))

**Comment by kmicklas** [comment]
Fixed by #422.
