### ISSUE TITLE
Using expressions from outer scope in nested scopes

### ISSUE THREAD

**Issue by ollef** [haskell-beam/beam#346]
If I have an expression in scope `s`, is it unsafe to use it in a `QNested s` scope? An example is using an outer expression in an aggregate. I would have thought that passing expressions _into_ aggregates would be okay (but passing them _out_ is problematic), but I'm probably missing something.

If it's safe, how is it done? I've not been able to find info on this in the docs or API reference.

Cheers!

**Comment by tathougies** [comment]
Can you provide an example? My thinking is that, typically, it ought to be fine, but I've found most of the time (if not all the time), I can work around this using polymorphism.

**Comment by ollef** [comment]
Sure. Hopefully this makes sense out of context.

It's a query to get some data about the all the message threads a user (participant) is involved in from a few different tables. Among other things, I wanted to get a list of names of all the participants in the thread, so something like this:

```haskell
threadSummaries participant = do
  thread <- threadByParticipant participant
  otherData <- getSomeOtherThreadData thread
  participantNames <- aggregate_
    (\accountData -> pgArrayAgg $ accountData ^. Account.name)
    $ do
      participant <- participantByThread thread
      accountByUuid participant
  return (thread, otherData, participantNames)
```

But the usage of `thread` in the `aggregate_` is not allowed because it's in a nested context.

The workaround is to filter by thread outside the aggregate. Something like this:

```haskell
threadSummaries participant = do
  thread <- threadByParticipant participant
  otherData <- getSomeOtherThreadData thread
  participantNames <- 
    fmap snd
    $ filter_ (\(tuuid, _) -> tuuid ==. thread ^. Thread.uuid)
    $ aggregate_
    (\(thread, accountData) -> (group_ $ thread ^. Thread.uuid, pgArrayAgg $ accountData ^. Account.name))
    $ do
      thread <- all_ DB.thread
      participant <- participantByThread thread
      accountData <- accountByUuid participant
      return (thread, accountData)
  return (thread, otherData, participantNames)
```

Not quite as straightforward, and perhaps not what you'd do directly in SQL.

**Comment by ocharles** [comment]
It's also helpful to consider what the ideal SQL would be. I believe you first example can be done, but it requires a `LATERAL` join condition on the aggregation.

**Comment by ollef** [comment]
I wouldn't know if it's ideal because I'm not very good at SQL but when I did this in plain SQL I was doing some left joins to get the account data for the participants, and took an `ARRAY_AGG` on fields from that (filtering out the nulls from the left joins). Something like this:

```sql
      SELECT
        ...,
        ARRAY_AGG(a_other.name) FILTER (WHERE a_other.account IS NOT NULL),
      FROM (SELECT * FROM message_thread_participant WHERE account = ?) AS tp_this
      INNER JOIN message_thread t ON t.uuid = tp_this.thread
      LEFT JOIN message_thread_participant tp_other ON tp_other.thread = t.uuid
      LEFT JOIN account_data a_other ON a_other.account = tp_other.account
      GROUP BY t.uuid, ...
```

I couldn't figure out how to express that in Beam, however.

**Comment by ollef** [comment]
Now that I've [learned a bit more about how scopes work](https://www.haste-lang.org/pubs/selda-paper.pdf) in libraries like Beam and Selda I think the answer is that no, allowing this would produce invalid SQL unless the aggregates compiled to lateral subqueries. I'm closing this now.

**Comment by tathougies** [comment]
FWIW, the beam-postgres module does indeed support lateral subqueries, and handles the rescoping properly for you:  http://hackage.haskell.org/package/beam-postgres-0.5.0.0/docs/Database-Beam-Postgres-Full.html#v:lateral_

Please open a new issue if you need help using it.
