### ISSUE TITLE
Add instance for SqlSerial Int64, to support BIGSERIAL

### ISSUE THREAD

**Issue by soverysour** [haskell-beam/beam#403]
Hi,

I'm referring to the **beam-postgres** backend.

I was using `SqlSerial Int`, which translates into `SERIAL`, and I wanted to bump it up to `BIGSERIAL`, however, only the instance for `Int` is provided.

I've looked around and found that there's no `bigint` type coming from [here](https://hackage.haskell.org/package/beam-postgres-0.4.0.0/docs/src/Database.Beam.Postgres.Types.html#line-171), as it is for `intType`, which is why I think an SqlSerial for BigInt was forgotten.

I've looked at [how serials are defined](https://hackage.haskell.org/package/beam-postgres-0.4.0.0/docs/src/Database.Beam.Postgres.Syntax.html#pgBigSerialType), where the `pgSerialType`, the normal serial type, is used to provide the `SqlSerial Int` instance.

I've gone and created an orphan instance for `Int64`, so that I can have `BIGSERIAL`s, like this:

```haskell
instance HasDefaultSqlDataType Postgres (SqlSerial Int64) where
  defaultSqlDataType _ _ False = pgBigSerialType
  defaultSqlDataType _ _ True = PgDataTypeSyntax (PgDataTypeDescrOid (Pg.typoid Pg.int8) Nothing) (emit "BIGINT") (pgDataTypeJSON "bigint")
```
Where all the data constructors and qualified modules are exactly like from [here](https://hackage.haskell.org/package/beam-postgres-0.4.0.0/docs/src/Database.Beam.Postgres.Syntax.html#pgBigSerialType), and it all works great! Migrations are properly generated (using `autoMigrate` and `defaultMigratableDbSettings`), i.e. the serials are `BIGSERIAL`s, and foreign keys are `bigint`s.

What do you think? @tathougies .

**Comment by kmicklas** [comment]
This will be fixed by #329.

**Comment by soverysour** [comment]
Another thing that I realized after doing this, would `countAll_` (and whatever related function there is) need to have its signature changed because of this? @kmicklas.

Currently, `countAll_` [returns an Int](https://hackage.haskell.org/package/beam-core-0.8.0.0/docs/Database-Beam-Query.html#v:countAll_) - would it need to return an `Int64`, or a `Num a => ...something` ?

**Comment by kmicklas** [comment]
Yeah I think it should return an explicitly sized integer. I know postgres `COUNT` is `bigint`/`Int64`.
