### ISSUE TITLE
Get QExprToField in insertOnly from insertData

### ISSUE THREAD

**Issue by ners** [haskell-beam/beam#452]
Could you please add a doc example for `insertOnly` with `insertData`? I cannot for the life of me figure out how to get a `QExprToField r` from raw values to be inserted. Thanks!

Use case: we have a table `(id Int, a Text, b Text)` and want to insert a list of `a` (`[Text]`), leaving `id` and `b` default.

**Comment by maerten** [comment]
Found an example in the closed issues section: https://github.com/haskell-beam/beam/issues/64#issuecomment-379484204

**Comment by kmicklas** [comment]
Also worth noting that you can insert default values with `default_`:

```haskell
MyTable 
  { _id = default_
  , _a = val_ a
  , _b = default_
  }
```

Closing this but feel free to reopen if you're still having difficulties!
