### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kozross** [haskell-beam/beam#460]
Even though bounds-widening for supporting GHC 8.8 has been done (except for #459), there is no release with this in effect, or even a revision. Could we get one of those please? This is blocking [one of our packages][beam-mysql].

[beam-mysql]: https://github.com/juspay/beam-mysql/issues/1

**Comment by 414owen** [comment]
Would also love to see a release compatible with GHC 8.8!

**Comment by runeksvendsen** [comment]
I'd like to second this. Is there a reason not to release `beam-core` from master to Hackage, so that 0.9.0.0 is available here?

**Comment by k0ral** [comment]
Looking at the [fixing PR](https://github.com/haskell-beam/beam/pull/463), there is no code changes involved, which suggests that simply creating a new [**revision**](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) would suffice (as opposed to a new release.)

**Comment by tathougies** [comment]
The latest beam-0.9.0.0 is now available on hackage, along with beam-migrate, beam-sqlite, and beam-postgres. Stay tuned for beam-mysql updates: http://hackage.haskell.org/package/beam-core
