### ISSUE TITLE
beam-postgres should not use cursors by default

### ISSUE THREAD

**Issue by lpsmith** [haskell-beam/beam#474]
While fighting a production fire yesterday involving an slow SQL query,  I discovered that beam-postgres uses cursors for literally every user query.  Cursors are occasionally useful in specialized cases,  but probably not worth it in typical use cases.   This definitely should not be default behavior.

Disadvantages of cursors:

1.  More round trips,  more overhead,  greater latency

2.  interacts badly with `log_min_duration_statement`,  making performance troubleshooting much more difficult.   Here's an anonymized excerpt of the actual log from yesterday with `log_min_duration_statement = 1000`.

```
Jun 08 15:10:23 postgresql-start[16980]: LOG:  duration: 2388.583 ms  statement: FETCH FORWARD 256 FROM temp26
Jun 08 15:10:23 postgresql-start[16980]: LOG:  duration: 3247.626 ms  statement: FETCH FORWARD 256 FROM temp6
Jun 08 15:10:24 postgresql-start[16980]: LOG:  duration: 2848.849 ms  statement: FETCH FORWARD 256 FROM temp26
Jun 08 15:10:25 postgresql-start[16980]: LOG:  duration: 4216.754 ms  statement: FETCH FORWARD 256 FROM temp26
```

Without logging the corresponding `DECLARE`  cursor statement, which is almost always very fast,  none of these log lines are actionable.  So we had to resort to `log_min_duration_statement = 0` and finding long-running fetch forward statements and then find corresponding declare cursor statements.    Furthermore,  at least with the version of postgres we are currently using for this project (`9.6`, I believe) even with `log_min_duration_statement = 0` we weren't always getting the declare queries in the log,  and I experimented with `log_statement` and `log_duration` with no luck.  (Unfortunately `log_duration` is almost entirely useless in production, as it logs the statements and durations in separate log lines in a racy way, so the correspondence between durations and statements is frequently ambiguous.  Using `log_min_duration_statement` in conjunction with `log_statement` results in the same behavior,  and not (as I was hoping) logging every statement twice,  one with a duration.  But I digress, as this is likely a postgres bug)

There are probably more disadvantages, but these are what came to mind.

Use cases for cursors:

1.  Streaming results out of the database,  thus reducing memory requirements of the database clients when dealing with result sets with large number of rows,  and reducing end-to-end latency from the database to the downstream consumer.   This is one of the classical use case for cursors,  though it's only really useful when you can live with the concurrency implications of `REPEATABLE READ` or lower transaction isolation levels,  as correctly-used `SERIALIZABLE` transactions are fundamentally incompatible with streaming.   (Also, it's worth noting that `PQsetSingleRowMode` is a more recent alternative for streaming, though it's not easily interruptable,  unlike cursors)

2.  Summarize results on the client:  this is potentially useful with `SERIALIZABLE` transactions, but there are ton of caveats:  have a large number of rows,  actually reduce the results in such a way that memory consumption on the client goes down,  be prepared to ignore the result if `SERIALIZABLE` fails to commit, etc.   And then it's often better to summarize on the database side using aggregation functions.

3.  Ability to interrupt a query part way through the execution:   say you only want some prefix of the result, but you don't know what that prefix is beforehand.  Cursors would be a way to do that.  This is getting pretty niche, admittedly.

There are even more niche use cases for cursors (e.g. I used them for pagination once,  on an database administration interface that never had more than a few concurrent users)  but these are pretty much what comes to my mind.

In any case, while cursors are occasionally useful,  using them for literally everything isn't a great idea.

**Comment by tathougies** [comment]
Do you have a recommendation for a better abstraction? I believe I chose cursors because beam-postgres's most primitive way to access results is a streaming interface, and everything is built on top of that, but we could probably specialize the `runReturningList` functions to not use cursors.

**Comment by istathar** [comment]
We appear to have encountered this in the wild as well. "Production fire" indeed. `FETCH FORWARD 256 FROM temp` was the only indication we had in the database monitoring, initially.

**Comment by tathougies** [comment]
So I think the *best* outcome here is to specialize the non-streaming functions to return the fully retrieved batch of data directly, instead of going through cursors. This should be straightforwards to do. Thanks for the bug report and the detailed discussion. If anyone is so inclined, I would appreciate it if someone would send an MR in to update the docs about the various subtleties here, since I myself am not sure I fully understand them.

**Comment by tathougies** [comment]
I'll also point out that this is an underlying problem with postgresql-simple. The library docs there say to use `fold` (which uses cursors) for better performance, but it seems that this has its own issues. Beam uses the same mechanisms as postgresql-simple, but I think it's okay to offer two separate interfaces.

**Comment by kmicklas** [comment]
Closing this as #520 should address the common case. We can definitely document this better though.
