### ISSUE TITLE
haskellSchema will fail if any table in the schema has no PK

### ISSUE THREAD

**Issue by o1lo01ol1o** [haskell-beam/beam#494]
This is an additional consequence of #447 but I didn't see that issue until after I had debugged `haskellSchema` far enough to understand that `TableHasPrimaryKey "table" []` is not satisfiable.

**Comment by kmicklas** [comment]
@o1lo01ol1o I believe this is fixed now by #495, please reopen if I'm mistaken. (Unfortunately we don't have tests for this yet.)
