### ISSUE TITLE
Clean up integer size handling

### ISSUE THREAD

**Issue by kmicklas** [haskell-beam/beam#496]
#329 greatly improved support for different integer sizes, however this introduced more issues and confusion (for example #493).

These are the steps I think we should take to rectify the situation:

 * Make all implementation-specific functions (e.g. `pgUnnestArrayWithOrdinality`) use correct explicitly sized integers (in that case `Int64` for `bigint`).
 * Create a type family for the cardinality returned by `COUNT` and the like, and use this to correct combinators that return `Int` like `countAll_`. Alternatively, make these polymorphic over any `Integral` like `count_`.
 * Remove the `Int` instances and add a custom type error directing the user to use explicitly sized integers.

Ideally we don't support `Int` anywhere since it's ambiguous in Haskell and database interop isn't something you generally want to leave to chance.

I'd like to get this in before the next release since it's a fairly large breaking change.

**Comment by 3noch** [comment]
Oof great points. Yes this seems very important.
