### ISSUE TITLE
Atomic update: how to use output of "SELECT ... FOR UPDATE" as input to update? (Postgres)

### ISSUE THREAD

**Issue by runeksvendsen** [haskell-beam/beam#527]
Hi there,

I'm trying to write a query using `beam-postgres` that combines a row-level lock with an update, in order to achieve an atomic update of a column in a single row ([from this article](https://layerci.com/blog/postgres-is-the-answer/)). The query looks like this:

```pgsql
UPDATE
  calculations
SET
  start_time = CURRENT_TIMESTAMP
WHERE
  id = (
    SELECT
      id
    FROM
      calculations
    WHERE
      start_time IS NULL
    LIMIT
      1
    FOR UPDATE
      SKIP LOCKED
  );
```

I've successfully written the SELECT subquery (see below), but I can't figure out how to combine this with `update` to arrive at the above query.

```haskell
selectQ =
    limit_ 1 $
    Pg.lockingFor_ Pg.PgSelectLockingStrengthUpdate (Just Pg.PgSelectLockingOptionsSkipLocked) $ do
        (calcLock, calculation) <- Pg.locked_ (calculations liquidityDb)
        guard_ $ isNothing_ (Calc.calculationStartTime calculation)
        pure (calculation `Pg.withLocks_` calcLock)
```

**Comment by tathougies** [comment]
```
lockedUpdate =
  update (calculations liquidityDb)
         (\calculation -> calculationStartTime calculatior <-. currentTimestamp_)
         (\calculation ->
           calculationId calculation ==.
             (subquery_ $ limit_ 1 $
              Pg.lockingFor_ Pg.PgSelectLockingStrengthUpdate (Just Pg.PgSelectLockingOptionsSkipLocked) $ do
                (calcLock, calculation) <- Pg.locked_ (calculations liquidityDb)
                guard_ $ isNothing_ (Calc.calculationStartTime calculation)
                pure (calculation `Pg.withLocks_` calcLock)))
```

**Comment by tathougies** [comment]
The key is that [`subquery_`](https://hackage.haskell.org/package/beam-core-0.9.0.0/docs/Database-Beam-Query.html#v:subquery_) can transform an arbitrary query (a value embedded in `Q`, which represents a calculation over relations) into a `QExpr` (which represents a particular value that can be used to select values from relations).

**Comment by tathougies** [comment]
There's currently no explanation of this in the manual. Feel free to add one!

**Comment by runeksvendsen** [comment]
Wonderful! Thank you very much. I will be adding this to the guide. 

Which part of the guide do you think it should be added to? 
The “Expressions” chapter has a subsection “SQL Functions and operators” which mentions “subquery_”, so perhaps somewhere in this chapter?

**Comment by tathougies** [comment]
Yeah, I think subquery_ can be expanded on in the expressions section.

And maybe provide the example for the postgres specific stuff in the
postgres session

Travis Athougies

**Comment by runeksvendsen** [comment]
@tathougies I've made an attempt at writing the relevant manual-section in #529. I'm neither an expert in SQL nor beam, so please feel free to edit to your liking.

I haven't written the Postgres-specific section since the use of `subquery_` in the Postgres-example doesn't differ from how it's used in the general case (use `subquery_` to turn a `Q` into a `QExpr`).
