### ISSUE TITLE
Does Beam support general algebraic sum types?

### ISSUE THREAD

**Issue by H2CO3** [haskell-beam/beam#528]
Hi,

The title says it all. I saw that it is possible to use a `data` type with all unit variants by delegating serialization to its `Show` and `Read` instances. But is it possible to represent general sum types (i.e. those of which the constructors take some associated data as well) in tables, rather than simply stringifying them?

Thanks!

**Comment by kmicklas** [comment]
SQL doesn't have sum types so there's no canonical way to encode them. There are a few possible strategies but it's not obvious to me how we could support it in a way that's in line with Beam's general philosophy. If you have any ideas let us know!

**Comment by H2CO3** [comment]
Thanks, that explains it!
