### ISSUE TITLE
A couple questions about migrations

### ISSUE THREAD

**Issue by thomasjm** [haskell-beam/beam#543]
Hi, apologies in advance if this is the wrong venue but I had a couple questions about the migrations system I was having trouble figuring out.

1) Is it possible to write a migration to define a view? I saw that you can use a view in a database by using `ViewEntity` instead of `TableEntity`, but I'm not seeing a way to actually create one (i.e. from a SQL query).
2) Is it possible to write a migration to define a UNIQUE constraint on multiple columns? It's easy to do on a single column by adding `unique` to the field but doing it on multiple columns has escaped me. (Although I've been able to make multi-column primary keys, which is great.)

**Comment by tathougies** [comment]
Hi, `beam-migrate` is still very much a WIP. Not everything is implemented. The SQL DDL space is very large.

Currently, I don't believe there's any way to create a view, but I can help guide you through the process of adding that functionality.

Same with UNIQUE constraints.
