### ISSUE TITLE
Add link to documentation site

### ISSUE THREAD

**Issue by ad-si** [haskell-beam/beam#550]
I don't know how many times I arrived here on GitHub looking for the link to the documentation (https://haskell-beam.github.io/beam/) 🙈. Can you maybe please add it to the official GitHub field on the repo page?

![image](https://user-images.githubusercontent.com/36796532/107882619-4ee18980-6ee2-11eb-952b-bfef3c30d785.png)

**Comment by kmicklas** [comment]
Thanks for pointing this out, done!
