### ISSUE TITLE
Postgres UUID can't be used in values_ (+ fix)

### ISSUE THREAD

**Issue by roberth** [haskell-beam/beam#555]
The postgresql backend generates UUID strings without a type. Most of the time PostgreSQL is clever enough to infer the type, but when used in `values_`, it only infers locally, leading to missing cast errors down the line. This can be fixed by always appending `::uuid` to UUIDs.
I haven't made a PR because I don't know where/how this should be changed. `beam-postgres` seems to borrow a lot of value syntax from `postgresql-simple`, which I'm not familiar with.
For my own application, I was able to change the syntax in my UUID newtype.

```haskell
instance HasSqlValueSyntax PgValueSyntax (Id a) where
  sqlValueSyntax (Id uuid) = PgValueSyntax $ fromPgValue (sqlValueSyntax uuid) <> emit "::uuid"
```

**Comment by kmicklas** [comment]
This looks like a `postgres-simple` bug but we could work around it by replacing `DEFAULT_SQL_SYNTAX(UUID)` with your instance.

**Comment by kmicklas** [comment]
I've reported https://github.com/lpsmith/postgresql-simple/issues/277 to see if it's possible to get this fixed upstream.
