### ISSUE TITLE
Type inference problems when trying to introduce additional data types

### ISSUE THREAD

**Issue by thomasjm** [haskell-beam/beam#558]
I'm interested in defining an additional data type so that I can return a subset of the columns of a table. Consider a simple type that wraps a `Text`, used to pull the "username" from a `users` table: 

```haskell
data FooT f = Foo (Columnar f Text)
  deriving (Generic, Beamable)
type Foo = FooT Identity

getFoos = runSQL $ do
  runSelectReturningList $ select $ do
    u <- all_ (_users db)
    pure $ Foo (_username u)
```

This fails to typecheck, with the error `Could not deduce: QExprToIdentity (FooT f0) ~ Foo`.

I can fix it by turning on `TypeAnnotations` and replacing `Foo` with `Foo @(QExpr be QBaseScope)`. However, adding the manual type annotations gets nastier as the types get more complex. Is there some way to do this sort of thing without running into type inference problems? Thanks!

(I know that I can just return a plain `Text` or tuple for simple cases like this, or just return the entire row object -- my eventual goal is to do more complicated things like extract columns from multiple tables with a `union_`, in which case having an intermediate type like this seems necessary.)

**Comment by thomasjm** [comment]
FWIW, I've had some success by moving the query into its own function, where it can have a type signature with a `forall`. Something like this:

```haskell
fooQuery :: forall be db s. (Database be db) => MyDb (DatabaseEntity be db) -> Q be db s (FooT (QExpr be s))
fooQuery theDb = do
  u <- all_ (_users theDb)
  pure $ Foo (_username u)
```

This seems to give the type system the hints it needs.

**Comment by kmicklas** [comment]
Unfortunately I'm not aware of any way we can make this work without explicit types somewhere.

The problem is that `Columnar` isn't injective. So you wouldn't have this problem if `Foo` contained another table object (which would be injective and determine `f`), for example.

As you discovered, making your queries explicity polymorphic is probably the cleanest solution.
