### ISSUE TITLE
Is it possible to use dynamically-generated table names?

### ISSUE THREAD

**Issue by JivanRoquet** [haskell-beam/beam#564]
Hello,

First off I must say I'm very impressed by the work done on Beam. The querying DSL in particular is amazing.

One question: is it possible to use dynamically generated table names?

We have a particular schema in a PostgreSQL database that contains several tables, which can't be known at compile-time (because they are created dynamically from another service). However, since they all share the same structure, we were thinking of doing something like this:

```haskell
data DynamicTableT f = DynamicTable
    { _dtSomeField     :: Columnar f Text
    , _dtAnotherField :: Columnar f Text
    , _dtOneMoreField  :: Columnar f Text}
    deriving Generic
```

However, two questions remain at this point:

- is it possible to teach Beam about the exact table name in a dynamic manner (so not at compile time)?
- can we use several such tables all based on the same Record (again, not at compile time)?

Example, at compile-time all we know is that there is a certain PostgreSQL schema that contains tables that all follow the same structure (same fields, same column names). But at runtime, we know that there will be 8 distinct such tables, and we get to know the exact names of the ones we need to query, at runtime only.

**Comment by kmicklas** [comment]
Yep, to query a table you need the `DatabaseEntity` value, which you would typically get from the `DatabaseSettings` record over your schema. This can be generated automatically with `defaultDbSettings`, but you can also define it manually, or override the generated names using `withDbModification`. See [database descriptors](https://haskell-beam.github.io/beam/user-guide/databases/#database-descriptors) in the user guide.

Once you have dynamically created `DatabaseEntity`s with the right table names, you can freely reuse the table type to query over these.

**Comment by kmicklas** [comment]
Closing this but feel free to reopen if you have any more trouble with this.
