### ISSUE TITLE
Duplicate Hashable instance declarations in beam-migrate-0.5.1.0 and hashable-1.3.4.1

### ISSUE THREAD

**Issue by metaml** [haskell-beam/beam#594]
This bug only appeared after I did a "cabal update." The "#if !MIN_VERSION_hashable(1, 3, 4)" may be the culprit but I'm not sure of the semantics  "!MIN_VERSION"

There seems to be a redundant instance in Beam that's defined in hashable-1.3.4.1. 

```
Database/Beam/Haskell/Syntax.hs:1041:10: error:
    Duplicate instance declarations:
      instance Hashable a => Hashable (S.Set a)
        -- Defined at Database/Beam/Haskell/Syntax.hs:1041:10
      instance Hashable v => Hashable (S.Set v)
        -- Defined in ‘hashable-1.3.4.1:Data.Hashable.Class’
     |
1041 | instance Hashable a => Hashable (S.Set a) where
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kmicklas** [comment]
@metaml I'm a bit confused, are you on master (which has `#if !MIN_VERSION_hashable(1, 3, 4)` around the instance) or the latest cabal release (which doesn't)?

**Comment by metaml** [comment]
That's odd, @kmicklas. I dug a bit, I think my bug may be a dupe of #592.
