### ISSUE TITLE
beam-core: support ghc-prim-0.8.0

### ISSUE THREAD

**Issue by jchia** [haskell-beam/beam#606]

**Comment by kmicklas** [comment]
Do you know if there is any incompatibility? Or do we just need to loosen the version bounds?

**Comment by jchia** [comment]
No, with the current master branch containing the recent changes, I don't know of any incompatibility or version bound problems. I'm just trying to include beam in stackage (after an updated hackage release) and currently the only blocker I can see is https://github.com/obsidiansystems/dependent-sum/issues/66
