### ISSUE TITLE
Build failure in beam-core-0.9.2.0 with GHC-8.2.2

### ISSUE THREAD

**Issue by sjakobi** [haskell-beam/beam#624]
```
Database/Beam/Backend/SQL/Builder.hs:58:10: error:
    Not in scope: type constructor or class ‘Semigroup’
   |
58 | instance Semigroup SqlSyntaxBuilder where
   |          ^^^^^^^^^
```

**Comment by sjakobi** [comment]
In order to detect compatibility issues like this one earlier, I recommend building with multiple GHC versions in CI. https://github.com/haskell-CI/haskell-ci makes this pretty easy in my experience.

**Comment by kmicklas** [comment]
We do build with multiple GHCs but only down to 8.6 since that's the oldest in nixpkgs. I think 8.6 is sufficiently old that I will remove support for 8.4 and we will avoid issues like this.
