### ISSUE TITLE
Unnecessary subquery layers in unionAll_ for Postgres

### ISSUE THREAD

**Issue by enobayram** [haskell-beam/beam#657]
I've noticed that `beam-postgres` will render the following beam expression:
``` haskell
orderBy_ someColumn $
  unionAll_
    (orderBy_ someColumn $ all_ someTable)
    (orderBy_ someColumn $ all_ otherTable)
```

as the following SQL query:

``` sql
SELECT <list-all-the-columns>
FROM (
  (
    SELECT <list-all-the-columns>
    FROM (
      SELECT <list-all-the-columns>
      FROM "someTable" AS "t0" 
      ORDER BY "t0"."someColumn"
    ) AS "t0"
  ) 
  UNION ALL 
  (
    SELECT <list-all-the-columns>
    FROM (
      SELECT <list-all-the-columns>
      FROM "otherTable" AS "t0" 
      ORDER BY "t0"."someColumn"
    ) AS "t0"
  )
) AS "t0" 
ORDER BY "t0"."someColumn"
```

While, for Postgres, the following is the same query:
``` sql
(
  SELECT <list-all-the-columns>
  FROM "someTable" AS "t0" 
  ORDER BY "t0"."someColumn"
) 
UNION ALL 
(
  SELECT <list-all-the-columns>
  FROM "otherTable" AS "t0" 
  ORDER BY "t0"."someColumn"
)
ORDER BY "someColumn"
```

So it seems like beam is introducing 2 unnecessary layers of `SELECT ... FROM (<subqery>) AS "t0"` wrapping. In practice, this results in a lot of noise, particularly when `<list-all-the-columns>` is long.

Would it be possible, without introducing too much complexity to `beam`, to avoid one or both of these unnecessary wrappings?

**Comment by kmicklas** [comment]
It's definitely possible to do simplifications to the generated query, but it does add complexity and in general I think Postgres should be able to do the same thing very reliably. However if you find a case where Postgres doesn't optimize the unsimplified query appropriately, we could look into handling that in Beam.
