### ISSUE TITLE
beam-postgres: runBeamPostgres is so hard to find in doc

### ISSUE THREAD

**Issue by debug-ito** [haskell-beam/beam#663]
In [haddock](https://hackage.haskell.org/package/beam-postgres-0.5.3.0/docs/Database-Beam-Postgres.html#g:23), `runBeamPostgres` function is so hard to find.

Because it is one of the essential functions, it should be listed a lot earlier, say, the next to `Pg` type.

**Comment by LaurentRDC** [comment]
Good suggestion, thanks!
