### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by ysangkok** [haskell-beam/beam#699]
Beam was disabled in Stackage Nightly because of some outdated dependencies:

- tried beam-core-0.10.1.0, but its *library* requires aeson >=0.11 && < 2.2 and the snapshot contains aeson-2.2.1.0
- tried beam-core-0.10.1.0, but its *library* requires bytestring >=0.10 && < 0.12 and the snapshot contains bytestring-0.12.1.0
- tried beam-core-0.10.1.0, but its *library* requires ghc-prim >=0.5 && < 0.11 and the snapshot contains ghc-prim-0.11.0
- tried beam-core-0.10.1.0, but its *library* requires text >=1.2.2.0 && < 2.1 and the snapshot contains text-2.1.1
- tried beam-core-0.10.1.0, but its *library* requires vector-sized >=0.5 && < 1.6 and the snapshot contains vector-sized-1.6.1
        
see

* https://github.com/commercialhaskell/stackage/issues/7219
* https://github.com/commercialhaskell/stackage/issues/7222
* https://github.com/commercialhaskell/stackage/issues/7216

**Comment by LaurentRDC** [comment]
I think #705 should fix this issue

**Comment by kmicklas** [comment]
Closing as I've merged #705. Feel free to reopen if there are still any missing bounds.

**Comment by ysangkok** [comment]
I can't reopen, but these are some of the bumps that still need to be done:

beam-core
---

```
$ cabal outdated
Outdated dependencies:
bytestring >=0.10 && <0.12 (latest: 0.12.1.0)
containers >=0.5 && <0.7 (latest: 0.7)
time >=1.6 && <1.13 (latest: 1.14)
```

Containers and bytestring are boot libraries in GHC 9.10: https://downloads.haskell.org/ghc/9.10.1/docs/users_guide/9.10.1-notes.html

beam-postgres
---

```
$ cabal outdated
Outdated dependencies:
bytestring >=0.10 && <0.12 (latest: 0.12.1.0)
time >=1.6 && <1.13 (latest: 1.14)
```

**Comment by ysangkok** [comment]
Would it be possible to make hackage revisions for these bumps: https://hackage.haskell.org/package/beam-core/maintain ?
