### ISSUE TITLE
`beam-postgres` broken in `NixPkgs/haskell-updates` and `NixPkgs`

### ISSUE THREAD

**Issue by peterbecich** [haskell-beam/beam#723]
Current error is
```
NIXPKGS_ALLOW_BROKEN=1 nix build nixpkgs/haskell-updates#haskellPackages.beam-postgres --impure

...
       > Error: Setup: Encountered missing or private dependencies:
       > tasty-discover >=4.2.1 && <4.3
```

I expect this to be partially solved if https://github.com/testcontainers/testcontainers-hs/pull/58 is merged and updated in NixPkgs.

When/if that happens, let's check the `nix build` above again.

It appears `beam-postgres` is not marked broken in NixPkgs:
https://github.com/NixOS/nixpkgs/blob/ec3ec6038a01c6e22637565976ed82e1625fa006/pkgs/development/haskell-modules/configuration-hackage2nix/broken.yaml#L388
However, `NIXPKGS_ALLOW_BROKEN=1` is necessary. That is probably the dependency on `beam` which is marked broken.

**Comment by alexfmpe** [comment]
Tracking this up...huh... downstream?
https://github.com/NixOS/nixpkgs/pull/356378
